// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coins.proto

package cn.chain33.javasdk.model.protobuf;

public final class CoinsProtobuf {
  private CoinsProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CoinsActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CoinsAction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.AssetsTransfer transfer = 1;</code>
     * @return Whether the transfer field is set.
     */
    boolean hasTransfer();
    /**
     * <code>.AssetsTransfer transfer = 1;</code>
     * @return The transfer.
     */
    cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer getTransfer();
    /**
     * <code>.AssetsTransfer transfer = 1;</code>
     */
    cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferOrBuilder getTransferOrBuilder();

    /**
     * <code>.AssetsWithdraw withdraw = 4;</code>
     * @return Whether the withdraw field is set.
     */
    boolean hasWithdraw();
    /**
     * <code>.AssetsWithdraw withdraw = 4;</code>
     * @return The withdraw.
     */
    cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw getWithdraw();
    /**
     * <code>.AssetsWithdraw withdraw = 4;</code>
     */
    cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdrawOrBuilder getWithdrawOrBuilder();

    /**
     * <code>.AssetsGenesis genesis = 2;</code>
     * @return Whether the genesis field is set.
     */
    boolean hasGenesis();
    /**
     * <code>.AssetsGenesis genesis = 2;</code>
     * @return The genesis.
     */
    cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis getGenesis();
    /**
     * <code>.AssetsGenesis genesis = 2;</code>
     */
    cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesisOrBuilder getGenesisOrBuilder();

    /**
     * <code>.AssetsTransferToExec transferToExec = 5;</code>
     * @return Whether the transferToExec field is set.
     */
    boolean hasTransferToExec();
    /**
     * <code>.AssetsTransferToExec transferToExec = 5;</code>
     * @return The transferToExec.
     */
    cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec getTransferToExec();
    /**
     * <code>.AssetsTransferToExec transferToExec = 5;</code>
     */
    cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExecOrBuilder getTransferToExecOrBuilder();

    /**
     * <code>int32 ty = 3;</code>
     * @return The ty.
     */
    int getTy();

    public cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction.ValueCase getValueCase();
  }
  /**
   * <pre>
   * message for execs.coins
   * </pre>
   *
   * Protobuf type {@code CoinsAction}
   */
  public static final class CoinsAction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CoinsAction)
      CoinsActionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CoinsAction.newBuilder() to construct.
    private CoinsAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CoinsAction() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CoinsAction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CoinsAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.Builder subBuilder = null;
              if (valueCase_ == 1) {
                subBuilder = ((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer) value_).toBuilder();
              }
              value_ =
                  input.readMessage(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 1;
              break;
            }
            case 18: {
              cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.Builder subBuilder = null;
              if (valueCase_ == 2) {
                subBuilder = ((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis) value_).toBuilder();
              }
              value_ =
                  input.readMessage(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 2;
              break;
            }
            case 24: {

              ty_ = input.readInt32();
              break;
            }
            case 34: {
              cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.Builder subBuilder = null;
              if (valueCase_ == 4) {
                subBuilder = ((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw) value_).toBuilder();
              }
              value_ =
                  input.readMessage(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 4;
              break;
            }
            case 42: {
              cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.Builder subBuilder = null;
              if (valueCase_ == 5) {
                subBuilder = ((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec) value_).toBuilder();
              }
              value_ =
                  input.readMessage(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 5;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.chain33.javasdk.model.protobuf.CoinsProtobuf.internal_static_CoinsAction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.chain33.javasdk.model.protobuf.CoinsProtobuf.internal_static_CoinsAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction.class, cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction.Builder.class);
    }

    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      TRANSFER(1),
      WITHDRAW(4),
      GENESIS(2),
      TRANSFERTOEXEC(5),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 1: return TRANSFER;
          case 4: return WITHDRAW;
          case 2: return GENESIS;
          case 5: return TRANSFERTOEXEC;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public static final int TRANSFER_FIELD_NUMBER = 1;
    /**
     * <code>.AssetsTransfer transfer = 1;</code>
     * @return Whether the transfer field is set.
     */
    @java.lang.Override
    public boolean hasTransfer() {
      return valueCase_ == 1;
    }
    /**
     * <code>.AssetsTransfer transfer = 1;</code>
     * @return The transfer.
     */
    @java.lang.Override
    public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer getTransfer() {
      if (valueCase_ == 1) {
         return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer) value_;
      }
      return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.getDefaultInstance();
    }
    /**
     * <code>.AssetsTransfer transfer = 1;</code>
     */
    @java.lang.Override
    public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferOrBuilder getTransferOrBuilder() {
      if (valueCase_ == 1) {
         return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer) value_;
      }
      return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.getDefaultInstance();
    }

    public static final int WITHDRAW_FIELD_NUMBER = 4;
    /**
     * <code>.AssetsWithdraw withdraw = 4;</code>
     * @return Whether the withdraw field is set.
     */
    @java.lang.Override
    public boolean hasWithdraw() {
      return valueCase_ == 4;
    }
    /**
     * <code>.AssetsWithdraw withdraw = 4;</code>
     * @return The withdraw.
     */
    @java.lang.Override
    public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw getWithdraw() {
      if (valueCase_ == 4) {
         return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw) value_;
      }
      return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.getDefaultInstance();
    }
    /**
     * <code>.AssetsWithdraw withdraw = 4;</code>
     */
    @java.lang.Override
    public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdrawOrBuilder getWithdrawOrBuilder() {
      if (valueCase_ == 4) {
         return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw) value_;
      }
      return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.getDefaultInstance();
    }

    public static final int GENESIS_FIELD_NUMBER = 2;
    /**
     * <code>.AssetsGenesis genesis = 2;</code>
     * @return Whether the genesis field is set.
     */
    @java.lang.Override
    public boolean hasGenesis() {
      return valueCase_ == 2;
    }
    /**
     * <code>.AssetsGenesis genesis = 2;</code>
     * @return The genesis.
     */
    @java.lang.Override
    public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis getGenesis() {
      if (valueCase_ == 2) {
         return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis) value_;
      }
      return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.getDefaultInstance();
    }
    /**
     * <code>.AssetsGenesis genesis = 2;</code>
     */
    @java.lang.Override
    public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesisOrBuilder getGenesisOrBuilder() {
      if (valueCase_ == 2) {
         return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis) value_;
      }
      return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.getDefaultInstance();
    }

    public static final int TRANSFERTOEXEC_FIELD_NUMBER = 5;
    /**
     * <code>.AssetsTransferToExec transferToExec = 5;</code>
     * @return Whether the transferToExec field is set.
     */
    @java.lang.Override
    public boolean hasTransferToExec() {
      return valueCase_ == 5;
    }
    /**
     * <code>.AssetsTransferToExec transferToExec = 5;</code>
     * @return The transferToExec.
     */
    @java.lang.Override
    public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec getTransferToExec() {
      if (valueCase_ == 5) {
         return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec) value_;
      }
      return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.getDefaultInstance();
    }
    /**
     * <code>.AssetsTransferToExec transferToExec = 5;</code>
     */
    @java.lang.Override
    public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExecOrBuilder getTransferToExecOrBuilder() {
      if (valueCase_ == 5) {
         return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec) value_;
      }
      return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.getDefaultInstance();
    }

    public static final int TY_FIELD_NUMBER = 3;
    private int ty_;
    /**
     * <code>int32 ty = 3;</code>
     * @return The ty.
     */
    @java.lang.Override
    public int getTy() {
      return ty_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (valueCase_ == 1) {
        output.writeMessage(1, (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer) value_);
      }
      if (valueCase_ == 2) {
        output.writeMessage(2, (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis) value_);
      }
      if (ty_ != 0) {
        output.writeInt32(3, ty_);
      }
      if (valueCase_ == 4) {
        output.writeMessage(4, (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw) value_);
      }
      if (valueCase_ == 5) {
        output.writeMessage(5, (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec) value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (valueCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer) value_);
      }
      if (valueCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis) value_);
      }
      if (ty_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ty_);
      }
      if (valueCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw) value_);
      }
      if (valueCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec) value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction)) {
        return super.equals(obj);
      }
      cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction other = (cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction) obj;

      if (getTy()
          != other.getTy()) return false;
      if (!getValueCase().equals(other.getValueCase())) return false;
      switch (valueCase_) {
        case 1:
          if (!getTransfer()
              .equals(other.getTransfer())) return false;
          break;
        case 4:
          if (!getWithdraw()
              .equals(other.getWithdraw())) return false;
          break;
        case 2:
          if (!getGenesis()
              .equals(other.getGenesis())) return false;
          break;
        case 5:
          if (!getTransferToExec()
              .equals(other.getTransferToExec())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TY_FIELD_NUMBER;
      hash = (53 * hash) + getTy();
      switch (valueCase_) {
        case 1:
          hash = (37 * hash) + TRANSFER_FIELD_NUMBER;
          hash = (53 * hash) + getTransfer().hashCode();
          break;
        case 4:
          hash = (37 * hash) + WITHDRAW_FIELD_NUMBER;
          hash = (53 * hash) + getWithdraw().hashCode();
          break;
        case 2:
          hash = (37 * hash) + GENESIS_FIELD_NUMBER;
          hash = (53 * hash) + getGenesis().hashCode();
          break;
        case 5:
          hash = (37 * hash) + TRANSFERTOEXEC_FIELD_NUMBER;
          hash = (53 * hash) + getTransferToExec().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * message for execs.coins
     * </pre>
     *
     * Protobuf type {@code CoinsAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CoinsAction)
        cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.chain33.javasdk.model.protobuf.CoinsProtobuf.internal_static_CoinsAction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.chain33.javasdk.model.protobuf.CoinsProtobuf.internal_static_CoinsAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction.class, cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction.Builder.class);
      }

      // Construct using cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ty_ = 0;

        valueCase_ = 0;
        value_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.chain33.javasdk.model.protobuf.CoinsProtobuf.internal_static_CoinsAction_descriptor;
      }

      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction getDefaultInstanceForType() {
        return cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction.getDefaultInstance();
      }

      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction build() {
        cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction buildPartial() {
        cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction result = new cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction(this);
        if (valueCase_ == 1) {
          if (transferBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = transferBuilder_.build();
          }
        }
        if (valueCase_ == 4) {
          if (withdrawBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = withdrawBuilder_.build();
          }
        }
        if (valueCase_ == 2) {
          if (genesisBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = genesisBuilder_.build();
          }
        }
        if (valueCase_ == 5) {
          if (transferToExecBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = transferToExecBuilder_.build();
          }
        }
        result.ty_ = ty_;
        result.valueCase_ = valueCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction) {
          return mergeFrom((cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction other) {
        if (other == cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction.getDefaultInstance()) return this;
        if (other.getTy() != 0) {
          setTy(other.getTy());
        }
        switch (other.getValueCase()) {
          case TRANSFER: {
            mergeTransfer(other.getTransfer());
            break;
          }
          case WITHDRAW: {
            mergeWithdraw(other.getWithdraw());
            break;
          }
          case GENESIS: {
            mergeGenesis(other.getGenesis());
            break;
          }
          case TRANSFERTOEXEC: {
            mergeTransferToExec(other.getTransferToExec());
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferOrBuilder> transferBuilder_;
      /**
       * <code>.AssetsTransfer transfer = 1;</code>
       * @return Whether the transfer field is set.
       */
      @java.lang.Override
      public boolean hasTransfer() {
        return valueCase_ == 1;
      }
      /**
       * <code>.AssetsTransfer transfer = 1;</code>
       * @return The transfer.
       */
      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer getTransfer() {
        if (transferBuilder_ == null) {
          if (valueCase_ == 1) {
            return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer) value_;
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.getDefaultInstance();
        } else {
          if (valueCase_ == 1) {
            return transferBuilder_.getMessage();
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.getDefaultInstance();
        }
      }
      /**
       * <code>.AssetsTransfer transfer = 1;</code>
       */
      public Builder setTransfer(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer value) {
        if (transferBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          transferBuilder_.setMessage(value);
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>.AssetsTransfer transfer = 1;</code>
       */
      public Builder setTransfer(
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.Builder builderForValue) {
        if (transferBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          transferBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>.AssetsTransfer transfer = 1;</code>
       */
      public Builder mergeTransfer(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer value) {
        if (transferBuilder_ == null) {
          if (valueCase_ == 1 &&
              value_ != cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.getDefaultInstance()) {
            value_ = cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.newBuilder((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 1) {
            transferBuilder_.mergeFrom(value);
          }
          transferBuilder_.setMessage(value);
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>.AssetsTransfer transfer = 1;</code>
       */
      public Builder clearTransfer() {
        if (transferBuilder_ == null) {
          if (valueCase_ == 1) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 1) {
            valueCase_ = 0;
            value_ = null;
          }
          transferBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.AssetsTransfer transfer = 1;</code>
       */
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.Builder getTransferBuilder() {
        return getTransferFieldBuilder().getBuilder();
      }
      /**
       * <code>.AssetsTransfer transfer = 1;</code>
       */
      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferOrBuilder getTransferOrBuilder() {
        if ((valueCase_ == 1) && (transferBuilder_ != null)) {
          return transferBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 1) {
            return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer) value_;
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.getDefaultInstance();
        }
      }
      /**
       * <code>.AssetsTransfer transfer = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferOrBuilder> 
          getTransferFieldBuilder() {
        if (transferBuilder_ == null) {
          if (!(valueCase_ == 1)) {
            value_ = cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.getDefaultInstance();
          }
          transferBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferOrBuilder>(
                  (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransfer) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 1;
        onChanged();;
        return transferBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdrawOrBuilder> withdrawBuilder_;
      /**
       * <code>.AssetsWithdraw withdraw = 4;</code>
       * @return Whether the withdraw field is set.
       */
      @java.lang.Override
      public boolean hasWithdraw() {
        return valueCase_ == 4;
      }
      /**
       * <code>.AssetsWithdraw withdraw = 4;</code>
       * @return The withdraw.
       */
      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw getWithdraw() {
        if (withdrawBuilder_ == null) {
          if (valueCase_ == 4) {
            return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw) value_;
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.getDefaultInstance();
        } else {
          if (valueCase_ == 4) {
            return withdrawBuilder_.getMessage();
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.getDefaultInstance();
        }
      }
      /**
       * <code>.AssetsWithdraw withdraw = 4;</code>
       */
      public Builder setWithdraw(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw value) {
        if (withdrawBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          withdrawBuilder_.setMessage(value);
        }
        valueCase_ = 4;
        return this;
      }
      /**
       * <code>.AssetsWithdraw withdraw = 4;</code>
       */
      public Builder setWithdraw(
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.Builder builderForValue) {
        if (withdrawBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          withdrawBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 4;
        return this;
      }
      /**
       * <code>.AssetsWithdraw withdraw = 4;</code>
       */
      public Builder mergeWithdraw(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw value) {
        if (withdrawBuilder_ == null) {
          if (valueCase_ == 4 &&
              value_ != cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.getDefaultInstance()) {
            value_ = cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.newBuilder((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 4) {
            withdrawBuilder_.mergeFrom(value);
          }
          withdrawBuilder_.setMessage(value);
        }
        valueCase_ = 4;
        return this;
      }
      /**
       * <code>.AssetsWithdraw withdraw = 4;</code>
       */
      public Builder clearWithdraw() {
        if (withdrawBuilder_ == null) {
          if (valueCase_ == 4) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 4) {
            valueCase_ = 0;
            value_ = null;
          }
          withdrawBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.AssetsWithdraw withdraw = 4;</code>
       */
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.Builder getWithdrawBuilder() {
        return getWithdrawFieldBuilder().getBuilder();
      }
      /**
       * <code>.AssetsWithdraw withdraw = 4;</code>
       */
      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdrawOrBuilder getWithdrawOrBuilder() {
        if ((valueCase_ == 4) && (withdrawBuilder_ != null)) {
          return withdrawBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 4) {
            return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw) value_;
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.getDefaultInstance();
        }
      }
      /**
       * <code>.AssetsWithdraw withdraw = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdrawOrBuilder> 
          getWithdrawFieldBuilder() {
        if (withdrawBuilder_ == null) {
          if (!(valueCase_ == 4)) {
            value_ = cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.getDefaultInstance();
          }
          withdrawBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdrawOrBuilder>(
                  (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsWithdraw) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 4;
        onChanged();;
        return withdrawBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesisOrBuilder> genesisBuilder_;
      /**
       * <code>.AssetsGenesis genesis = 2;</code>
       * @return Whether the genesis field is set.
       */
      @java.lang.Override
      public boolean hasGenesis() {
        return valueCase_ == 2;
      }
      /**
       * <code>.AssetsGenesis genesis = 2;</code>
       * @return The genesis.
       */
      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis getGenesis() {
        if (genesisBuilder_ == null) {
          if (valueCase_ == 2) {
            return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis) value_;
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.getDefaultInstance();
        } else {
          if (valueCase_ == 2) {
            return genesisBuilder_.getMessage();
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.getDefaultInstance();
        }
      }
      /**
       * <code>.AssetsGenesis genesis = 2;</code>
       */
      public Builder setGenesis(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis value) {
        if (genesisBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          genesisBuilder_.setMessage(value);
        }
        valueCase_ = 2;
        return this;
      }
      /**
       * <code>.AssetsGenesis genesis = 2;</code>
       */
      public Builder setGenesis(
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.Builder builderForValue) {
        if (genesisBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          genesisBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 2;
        return this;
      }
      /**
       * <code>.AssetsGenesis genesis = 2;</code>
       */
      public Builder mergeGenesis(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis value) {
        if (genesisBuilder_ == null) {
          if (valueCase_ == 2 &&
              value_ != cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.getDefaultInstance()) {
            value_ = cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.newBuilder((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 2) {
            genesisBuilder_.mergeFrom(value);
          }
          genesisBuilder_.setMessage(value);
        }
        valueCase_ = 2;
        return this;
      }
      /**
       * <code>.AssetsGenesis genesis = 2;</code>
       */
      public Builder clearGenesis() {
        if (genesisBuilder_ == null) {
          if (valueCase_ == 2) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 2) {
            valueCase_ = 0;
            value_ = null;
          }
          genesisBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.AssetsGenesis genesis = 2;</code>
       */
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.Builder getGenesisBuilder() {
        return getGenesisFieldBuilder().getBuilder();
      }
      /**
       * <code>.AssetsGenesis genesis = 2;</code>
       */
      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesisOrBuilder getGenesisOrBuilder() {
        if ((valueCase_ == 2) && (genesisBuilder_ != null)) {
          return genesisBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 2) {
            return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis) value_;
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.getDefaultInstance();
        }
      }
      /**
       * <code>.AssetsGenesis genesis = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesisOrBuilder> 
          getGenesisFieldBuilder() {
        if (genesisBuilder_ == null) {
          if (!(valueCase_ == 2)) {
            value_ = cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.getDefaultInstance();
          }
          genesisBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesisOrBuilder>(
                  (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsGenesis) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 2;
        onChanged();;
        return genesisBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExecOrBuilder> transferToExecBuilder_;
      /**
       * <code>.AssetsTransferToExec transferToExec = 5;</code>
       * @return Whether the transferToExec field is set.
       */
      @java.lang.Override
      public boolean hasTransferToExec() {
        return valueCase_ == 5;
      }
      /**
       * <code>.AssetsTransferToExec transferToExec = 5;</code>
       * @return The transferToExec.
       */
      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec getTransferToExec() {
        if (transferToExecBuilder_ == null) {
          if (valueCase_ == 5) {
            return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec) value_;
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.getDefaultInstance();
        } else {
          if (valueCase_ == 5) {
            return transferToExecBuilder_.getMessage();
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.getDefaultInstance();
        }
      }
      /**
       * <code>.AssetsTransferToExec transferToExec = 5;</code>
       */
      public Builder setTransferToExec(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec value) {
        if (transferToExecBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          transferToExecBuilder_.setMessage(value);
        }
        valueCase_ = 5;
        return this;
      }
      /**
       * <code>.AssetsTransferToExec transferToExec = 5;</code>
       */
      public Builder setTransferToExec(
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.Builder builderForValue) {
        if (transferToExecBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          transferToExecBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 5;
        return this;
      }
      /**
       * <code>.AssetsTransferToExec transferToExec = 5;</code>
       */
      public Builder mergeTransferToExec(cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec value) {
        if (transferToExecBuilder_ == null) {
          if (valueCase_ == 5 &&
              value_ != cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.getDefaultInstance()) {
            value_ = cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.newBuilder((cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 5) {
            transferToExecBuilder_.mergeFrom(value);
          }
          transferToExecBuilder_.setMessage(value);
        }
        valueCase_ = 5;
        return this;
      }
      /**
       * <code>.AssetsTransferToExec transferToExec = 5;</code>
       */
      public Builder clearTransferToExec() {
        if (transferToExecBuilder_ == null) {
          if (valueCase_ == 5) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 5) {
            valueCase_ = 0;
            value_ = null;
          }
          transferToExecBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.AssetsTransferToExec transferToExec = 5;</code>
       */
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.Builder getTransferToExecBuilder() {
        return getTransferToExecFieldBuilder().getBuilder();
      }
      /**
       * <code>.AssetsTransferToExec transferToExec = 5;</code>
       */
      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExecOrBuilder getTransferToExecOrBuilder() {
        if ((valueCase_ == 5) && (transferToExecBuilder_ != null)) {
          return transferToExecBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 5) {
            return (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec) value_;
          }
          return cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.getDefaultInstance();
        }
      }
      /**
       * <code>.AssetsTransferToExec transferToExec = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExecOrBuilder> 
          getTransferToExecFieldBuilder() {
        if (transferToExecBuilder_ == null) {
          if (!(valueCase_ == 5)) {
            value_ = cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.getDefaultInstance();
          }
          transferToExecBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec.Builder, cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExecOrBuilder>(
                  (cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.AssetsTransferToExec) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 5;
        onChanged();;
        return transferToExecBuilder_;
      }

      private int ty_ ;
      /**
       * <code>int32 ty = 3;</code>
       * @return The ty.
       */
      @java.lang.Override
      public int getTy() {
        return ty_;
      }
      /**
       * <code>int32 ty = 3;</code>
       * @param value The ty to set.
       * @return This builder for chaining.
       */
      public Builder setTy(int value) {
        
        ty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ty = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTy() {
        
        ty_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CoinsAction)
    }

    // @@protoc_insertion_point(class_scope:CoinsAction)
    private static final cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction();
    }

    public static cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CoinsAction>
        PARSER = new com.google.protobuf.AbstractParser<CoinsAction>() {
      @java.lang.Override
      public CoinsAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CoinsAction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CoinsAction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CoinsAction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.chain33.javasdk.model.protobuf.CoinsProtobuf.CoinsAction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CoinsAction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CoinsAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013coins.proto\032\021transaction.proto\"\300\001\n\013Coi" +
      "nsAction\022#\n\010transfer\030\001 \001(\0132\017.AssetsTrans" +
      "ferH\000\022#\n\010withdraw\030\004 \001(\0132\017.AssetsWithdraw" +
      "H\000\022!\n\007genesis\030\002 \001(\0132\016.AssetsGenesisH\000\022/\n" +
      "\016transferToExec\030\005 \001(\0132\025.AssetsTransferTo" +
      "ExecH\000\022\n\n\002ty\030\003 \001(\005B\007\n\005valueB2\n!cn.chain3" +
      "3.javasdk.model.protobufB\rCoinsProtobufb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.getDescriptor(),
        });
    internal_static_CoinsAction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CoinsAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CoinsAction_descriptor,
        new java.lang.String[] { "Transfer", "Withdraw", "Genesis", "TransferToExec", "Ty", "Value", });
    cn.chain33.javasdk.model.protobuf.TransactionAllProtobuf.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
