// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manage.proto

package cn.chain33.javasdk.model.protobuf;

public final class ManageProtobuf {
  private ManageProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ManageActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ManageAction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ModifyConfig modify = 1;</code>
     * @return Whether the modify field is set.
     */
    boolean hasModify();
    /**
     * <code>.ModifyConfig modify = 1;</code>
     * @return The modify.
     */
    cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig getModify();
    /**
     * <code>.ModifyConfig modify = 1;</code>
     */
    cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfigOrBuilder getModifyOrBuilder();

    /**
     * <code>int32 Ty = 2;</code>
     * @return The ty.
     */
    int getTy();

    public cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction.ValueCase getValueCase();
  }
  /**
   * Protobuf type {@code ManageAction}
   */
  public  static final class ManageAction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ManageAction)
      ManageActionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ManageAction.newBuilder() to construct.
    private ManageAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ManageAction() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ManageAction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ManageAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.Builder subBuilder = null;
              if (valueCase_ == 1) {
                subBuilder = ((cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig) value_).toBuilder();
              }
              value_ =
                  input.readMessage(cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 1;
              break;
            }
            case 16: {

              ty_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.chain33.javasdk.model.protobuf.ManageProtobuf.internal_static_ManageAction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.chain33.javasdk.model.protobuf.ManageProtobuf.internal_static_ManageAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction.class, cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction.Builder.class);
    }

    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      MODIFY(1),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 1: return MODIFY;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public static final int MODIFY_FIELD_NUMBER = 1;
    /**
     * <code>.ModifyConfig modify = 1;</code>
     * @return Whether the modify field is set.
     */
    public boolean hasModify() {
      return valueCase_ == 1;
    }
    /**
     * <code>.ModifyConfig modify = 1;</code>
     * @return The modify.
     */
    public cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig getModify() {
      if (valueCase_ == 1) {
         return (cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig) value_;
      }
      return cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.getDefaultInstance();
    }
    /**
     * <code>.ModifyConfig modify = 1;</code>
     */
    public cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfigOrBuilder getModifyOrBuilder() {
      if (valueCase_ == 1) {
         return (cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig) value_;
      }
      return cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.getDefaultInstance();
    }

    public static final int TY_FIELD_NUMBER = 2;
    private int ty_;
    /**
     * <code>int32 Ty = 2;</code>
     * @return The ty.
     */
    public int getTy() {
      return ty_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (valueCase_ == 1) {
        output.writeMessage(1, (cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig) value_);
      }
      if (ty_ != 0) {
        output.writeInt32(2, ty_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (valueCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig) value_);
      }
      if (ty_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ty_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction)) {
        return super.equals(obj);
      }
      cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction other = (cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction) obj;

      if (getTy()
          != other.getTy()) return false;
      if (!getValueCase().equals(other.getValueCase())) return false;
      switch (valueCase_) {
        case 1:
          if (!getModify()
              .equals(other.getModify())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TY_FIELD_NUMBER;
      hash = (53 * hash) + getTy();
      switch (valueCase_) {
        case 1:
          hash = (37 * hash) + MODIFY_FIELD_NUMBER;
          hash = (53 * hash) + getModify().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ManageAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ManageAction)
        cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.chain33.javasdk.model.protobuf.ManageProtobuf.internal_static_ManageAction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.chain33.javasdk.model.protobuf.ManageProtobuf.internal_static_ManageAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction.class, cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction.Builder.class);
      }

      // Construct using cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ty_ = 0;

        valueCase_ = 0;
        value_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.chain33.javasdk.model.protobuf.ManageProtobuf.internal_static_ManageAction_descriptor;
      }

      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction getDefaultInstanceForType() {
        return cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction.getDefaultInstance();
      }

      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction build() {
        cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction buildPartial() {
        cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction result = new cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction(this);
        if (valueCase_ == 1) {
          if (modifyBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = modifyBuilder_.build();
          }
        }
        result.ty_ = ty_;
        result.valueCase_ = valueCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction) {
          return mergeFrom((cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction other) {
        if (other == cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction.getDefaultInstance()) return this;
        if (other.getTy() != 0) {
          setTy(other.getTy());
        }
        switch (other.getValueCase()) {
          case MODIFY: {
            mergeModify(other.getModify());
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig, cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.Builder, cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfigOrBuilder> modifyBuilder_;
      /**
       * <code>.ModifyConfig modify = 1;</code>
       * @return Whether the modify field is set.
       */
      public boolean hasModify() {
        return valueCase_ == 1;
      }
      /**
       * <code>.ModifyConfig modify = 1;</code>
       * @return The modify.
       */
      public cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig getModify() {
        if (modifyBuilder_ == null) {
          if (valueCase_ == 1) {
            return (cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig) value_;
          }
          return cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.getDefaultInstance();
        } else {
          if (valueCase_ == 1) {
            return modifyBuilder_.getMessage();
          }
          return cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.getDefaultInstance();
        }
      }
      /**
       * <code>.ModifyConfig modify = 1;</code>
       */
      public Builder setModify(cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig value) {
        if (modifyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          modifyBuilder_.setMessage(value);
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>.ModifyConfig modify = 1;</code>
       */
      public Builder setModify(
          cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.Builder builderForValue) {
        if (modifyBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          modifyBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>.ModifyConfig modify = 1;</code>
       */
      public Builder mergeModify(cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig value) {
        if (modifyBuilder_ == null) {
          if (valueCase_ == 1 &&
              value_ != cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.getDefaultInstance()) {
            value_ = cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.newBuilder((cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 1) {
            modifyBuilder_.mergeFrom(value);
          }
          modifyBuilder_.setMessage(value);
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>.ModifyConfig modify = 1;</code>
       */
      public Builder clearModify() {
        if (modifyBuilder_ == null) {
          if (valueCase_ == 1) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 1) {
            valueCase_ = 0;
            value_ = null;
          }
          modifyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ModifyConfig modify = 1;</code>
       */
      public cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.Builder getModifyBuilder() {
        return getModifyFieldBuilder().getBuilder();
      }
      /**
       * <code>.ModifyConfig modify = 1;</code>
       */
      public cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfigOrBuilder getModifyOrBuilder() {
        if ((valueCase_ == 1) && (modifyBuilder_ != null)) {
          return modifyBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 1) {
            return (cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig) value_;
          }
          return cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.getDefaultInstance();
        }
      }
      /**
       * <code>.ModifyConfig modify = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig, cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.Builder, cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfigOrBuilder> 
          getModifyFieldBuilder() {
        if (modifyBuilder_ == null) {
          if (!(valueCase_ == 1)) {
            value_ = cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.getDefaultInstance();
          }
          modifyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig, cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig.Builder, cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfigOrBuilder>(
                  (cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.ModifyConfig) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 1;
        onChanged();;
        return modifyBuilder_;
      }

      private int ty_ ;
      /**
       * <code>int32 Ty = 2;</code>
       * @return The ty.
       */
      public int getTy() {
        return ty_;
      }
      /**
       * <code>int32 Ty = 2;</code>
       * @param value The ty to set.
       * @return This builder for chaining.
       */
      public Builder setTy(int value) {
        
        ty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Ty = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTy() {
        
        ty_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ManageAction)
    }

    // @@protoc_insertion_point(class_scope:ManageAction)
    private static final cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction();
    }

    public static cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ManageAction>
        PARSER = new com.google.protobuf.AbstractParser<ManageAction>() {
      @java.lang.Override
      public ManageAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ManageAction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ManageAction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ManageAction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.chain33.javasdk.model.protobuf.ManageProtobuf.ManageAction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ManageAction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ManageAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014manage.proto\032\016executor.proto\"D\n\014Manage" +
      "Action\022\037\n\006modify\030\001 \001(\0132\r.ModifyConfigH\000\022" +
      "\n\n\002Ty\030\002 \001(\005B\007\n\005valueB3\n!cn.chain33.javas" +
      "dk.model.protobufB\016ManageProtobufb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.getDescriptor(),
        });
    internal_static_ManageAction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ManageAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ManageAction_descriptor,
        new java.lang.String[] { "Modify", "Ty", "Value", });
    cn.chain33.javasdk.model.protobuf.ExecuterProtobuf.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
