// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transaction.proto

package cn.chain33.javasdk.model.protobuf;

/**
 * protobuff对象
 * @author logan
 * 2018年5月15日
 */
public final class TransactionProtoBuf {
  private TransactionProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Signature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 ty = 1;</code>
     */
    int getTy();

    /**
     * <code>bytes pubkey = 2;</code>
     */
    com.google.protobuf.ByteString getPubkey();

    /**
     * <code>bytes signature = 3;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code Signature}
   */
  public  static final class Signature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Signature)
      SignatureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Signature.newBuilder() to construct.
    private Signature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Signature() {
      ty_ = 0;
      pubkey_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Signature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      @SuppressWarnings("unused")
	int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              ty_ = input.readInt32();
              break;
            }
            case 18: {

              pubkey_ = input.readBytes();
              break;
            }
            case 26: {

              signature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.internal_static_Signature_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.internal_static_Signature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.class, cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.Builder.class);
    }

    public static final int TY_FIELD_NUMBER = 1;
    private int ty_;
    /**
     * <code>int32 ty = 1;</code>
     */
    public int getTy() {
      return ty_;
    }

    public static final int PUBKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString pubkey_;
    /**
     * <code>bytes pubkey = 2;</code>
     */
    public com.google.protobuf.ByteString getPubkey() {
      return pubkey_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 3;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ty_ != 0) {
        output.writeInt32(1, ty_);
      }
      if (!pubkey_.isEmpty()) {
        output.writeBytes(2, pubkey_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(3, signature_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ty_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ty_);
      }
      if (!pubkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, pubkey_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature)) {
        return super.equals(obj);
      }
      cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature other = (cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature) obj;

      boolean result = true;
      result = result && (getTy()
          == other.getTy());
      result = result && getPubkey()
          .equals(other.getPubkey());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @SuppressWarnings("unchecked")
	@java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TY_FIELD_NUMBER;
      hash = (53 * hash) + getTy();
      hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPubkey().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Signature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Signature)
        cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.SignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.internal_static_Signature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.internal_static_Signature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.class, cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.Builder.class);
      }

      // Construct using com.fuzamei.chain33api.coin.TransactionProtoBuf.Signature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ty_ = 0;

        pubkey_ = com.google.protobuf.ByteString.EMPTY;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.internal_static_Signature_descriptor;
      }

      public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature getDefaultInstanceForType() {
        return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.getDefaultInstance();
      }

      public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature build() {
        cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature buildPartial() {
        cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature result = new cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature(this);
        result.ty_ = ty_;
        result.pubkey_ = pubkey_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature) {
          return mergeFrom((cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature other) {
        if (other == cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.getDefaultInstance()) return this;
        if (other.getTy() != 0) {
          setTy(other.getTy());
        }
        if (other.getPubkey() != com.google.protobuf.ByteString.EMPTY) {
          setPubkey(other.getPubkey());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int ty_ ;
      /**
       * <code>int32 ty = 1;</code>
       */
      public int getTy() {
        return ty_;
      }
      /**
       * <code>int32 ty = 1;</code>
       */
      public Builder setTy(int value) {
        
        ty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ty = 1;</code>
       */
      public Builder clearTy() {
        
        ty_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes pubkey = 2;</code>
       */
      public com.google.protobuf.ByteString getPubkey() {
        return pubkey_;
      }
      /**
       * <code>bytes pubkey = 2;</code>
       */
      public Builder setPubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes pubkey = 2;</code>
       */
      public Builder clearPubkey() {
        
        pubkey_ = getDefaultInstance().getPubkey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 3;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 3;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 3;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Signature)
    }

    // @@protoc_insertion_point(class_scope:Signature)
    private static final cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature();
    }

    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Signature>
        PARSER = new com.google.protobuf.AbstractParser<Signature>() {
      public Signature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Signature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Signature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Signature> getParserForType() {
      return PARSER;
    }

    public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes execer = 1;</code>
     */
    com.google.protobuf.ByteString getExecer();

    /**
     * <code>bytes payload = 2;</code>
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>.Signature signature = 3;</code>
     */
    boolean hasSignature();
    /**
     * <code>.Signature signature = 3;</code>
     */
    cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature getSignature();
    /**
     * <code>.Signature signature = 3;</code>
     */
    cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.SignatureOrBuilder getSignatureOrBuilder();

    /**
     * <code>int64 fee = 4;</code>
     */
    long getFee();

    /**
     * <code>int64 Expire = 5;</code>
     */
    long getExpire();

    /**
     * <code>int64 nonce = 6;</code>
     */
    long getNonce();

    /**
     * <code>string to = 7;</code>
     */
    java.lang.String getTo();
    /**
     * <code>string to = 7;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();
  }
  /**
   * Protobuf type {@code Transaction}
   */
  public  static final class Transaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Transaction)
      TransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transaction() {
      execer_ = com.google.protobuf.ByteString.EMPTY;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      fee_ = 0L;
      expire_ = 0L;
      nonce_ = 0L;
      to_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    @SuppressWarnings("unused")
	private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              execer_ = input.readBytes();
              break;
            }
            case 18: {

              payload_ = input.readBytes();
              break;
            }
            case 26: {
              cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.Builder subBuilder = null;
              if (signature_ != null) {
                subBuilder = signature_.toBuilder();
              }
              signature_ = input.readMessage(cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(signature_);
                signature_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              fee_ = input.readInt64();
              break;
            }
            case 40: {

              expire_ = input.readInt64();
              break;
            }
            case 48: {

              nonce_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.internal_static_Transaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.internal_static_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction.class, cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction.Builder.class);
    }

    public static final int EXECER_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString execer_;
    /**
     * <code>bytes execer = 1;</code>
     */
    public com.google.protobuf.ByteString getExecer() {
      return execer_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 2;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 3;
    private cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature signature_;
    /**
     * <code>.Signature signature = 3;</code>
     */
    public boolean hasSignature() {
      return signature_ != null;
    }
    /**
     * <code>.Signature signature = 3;</code>
     */
    public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature getSignature() {
      return signature_ == null ? cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.getDefaultInstance() : signature_;
    }
    /**
     * <code>.Signature signature = 3;</code>
     */
    public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.SignatureOrBuilder getSignatureOrBuilder() {
      return getSignature();
    }

    public static final int FEE_FIELD_NUMBER = 4;
    private long fee_;
    /**
     * <code>int64 fee = 4;</code>
     */
    public long getFee() {
      return fee_;
    }

    public static final int EXPIRE_FIELD_NUMBER = 5;
    private long expire_;
    /**
     * <code>int64 Expire = 5;</code>
     */
    public long getExpire() {
      return expire_;
    }

    public static final int NONCE_FIELD_NUMBER = 6;
    private long nonce_;
    /**
     * <code>int64 nonce = 6;</code>
     */
    public long getNonce() {
      return nonce_;
    }

    public static final int TO_FIELD_NUMBER = 7;
    private volatile java.lang.Object to_;
    /**
     * <code>string to = 7;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>string to = 7;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!execer_.isEmpty()) {
        output.writeBytes(1, execer_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(2, payload_);
      }
      if (signature_ != null) {
        output.writeMessage(3, getSignature());
      }
      if (fee_ != 0L) {
        output.writeInt64(4, fee_);
      }
      if (expire_ != 0L) {
        output.writeInt64(5, expire_);
      }
      if (nonce_ != 0L) {
        output.writeInt64(6, nonce_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, to_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!execer_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, execer_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      if (signature_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSignature());
      }
      if (fee_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, fee_);
      }
      if (expire_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, expire_);
      }
      if (nonce_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, nonce_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, to_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction)) {
        return super.equals(obj);
      }
      cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction other = (cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction) obj;

      boolean result = true;
      result = result && getExecer()
          .equals(other.getExecer());
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && (hasSignature() == other.hasSignature());
      if (hasSignature()) {
        result = result && getSignature()
            .equals(other.getSignature());
      }
      result = result && (getFee()
          == other.getFee());
      result = result && (getExpire()
          == other.getExpire());
      result = result && (getNonce()
          == other.getNonce());
      result = result && getTo()
          .equals(other.getTo());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @SuppressWarnings("unchecked")
	@java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXECER_FIELD_NUMBER;
      hash = (53 * hash) + getExecer().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      hash = (37 * hash) + FEE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFee());
      hash = (37 * hash) + EXPIRE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpire());
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNonce());
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Transaction)
        cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.internal_static_Transaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.internal_static_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction.class, cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction.Builder.class);
      }

      // Construct using com.fuzamei.chain33api.coin.TransactionProtoBuf.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        execer_ = com.google.protobuf.ByteString.EMPTY;

        payload_ = com.google.protobuf.ByteString.EMPTY;

        if (signatureBuilder_ == null) {
          signature_ = null;
        } else {
          signature_ = null;
          signatureBuilder_ = null;
        }
        fee_ = 0L;

        expire_ = 0L;

        nonce_ = 0L;

        to_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.internal_static_Transaction_descriptor;
      }

      public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction getDefaultInstanceForType() {
        return cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction.getDefaultInstance();
      }

      public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction build() {
        cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction buildPartial() {
        cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction result = new cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction(this);
        result.execer_ = execer_;
        result.payload_ = payload_;
        if (signatureBuilder_ == null) {
          result.signature_ = signature_;
        } else {
          result.signature_ = signatureBuilder_.build();
        }
        result.fee_ = fee_;
        result.expire_ = expire_;
        result.nonce_ = nonce_;
        result.to_ = to_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction) {
          return mergeFrom((cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction other) {
        if (other == cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction.getDefaultInstance()) return this;
        if (other.getExecer() != com.google.protobuf.ByteString.EMPTY) {
          setExecer(other.getExecer());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        if (other.hasSignature()) {
          mergeSignature(other.getSignature());
        }
        if (other.getFee() != 0L) {
          setFee(other.getFee());
        }
        if (other.getExpire() != 0L) {
          setExpire(other.getExpire());
        }
        if (other.getNonce() != 0L) {
          setNonce(other.getNonce());
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString execer_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes execer = 1;</code>
       */
      public com.google.protobuf.ByteString getExecer() {
        return execer_;
      }
      /**
       * <code>bytes execer = 1;</code>
       */
      public Builder setExecer(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        execer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes execer = 1;</code>
       */
      public Builder clearExecer() {
        
        execer_ = getDefaultInstance().getExecer();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 2;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature signature_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature, cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.Builder, cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.SignatureOrBuilder> signatureBuilder_;
      /**
       * <code>.Signature signature = 3;</code>
       */
      public boolean hasSignature() {
        return signatureBuilder_ != null || signature_ != null;
      }
      /**
       * <code>.Signature signature = 3;</code>
       */
      public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature getSignature() {
        if (signatureBuilder_ == null) {
          return signature_ == null ? cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.getDefaultInstance() : signature_;
        } else {
          return signatureBuilder_.getMessage();
        }
      }
      /**
       * <code>.Signature signature = 3;</code>
       */
      public Builder setSignature(cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature value) {
        if (signatureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          signature_ = value;
          onChanged();
        } else {
          signatureBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Signature signature = 3;</code>
       */
      public Builder setSignature(
          cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.Builder builderForValue) {
        if (signatureBuilder_ == null) {
          signature_ = builderForValue.build();
          onChanged();
        } else {
          signatureBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Signature signature = 3;</code>
       */
      public Builder mergeSignature(cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature value) {
        if (signatureBuilder_ == null) {
          if (signature_ != null) {
            signature_ =
              cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.newBuilder(signature_).mergeFrom(value).buildPartial();
          } else {
            signature_ = value;
          }
          onChanged();
        } else {
          signatureBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Signature signature = 3;</code>
       */
      public Builder clearSignature() {
        if (signatureBuilder_ == null) {
          signature_ = null;
          onChanged();
        } else {
          signature_ = null;
          signatureBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Signature signature = 3;</code>
       */
      public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.Builder getSignatureBuilder() {
        
        onChanged();
        return getSignatureFieldBuilder().getBuilder();
      }
      /**
       * <code>.Signature signature = 3;</code>
       */
      public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.SignatureOrBuilder getSignatureOrBuilder() {
        if (signatureBuilder_ != null) {
          return signatureBuilder_.getMessageOrBuilder();
        } else {
          return signature_ == null ?
              cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.getDefaultInstance() : signature_;
        }
      }
      /**
       * <code>.Signature signature = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature, cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.Builder, cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.SignatureOrBuilder> 
          getSignatureFieldBuilder() {
        if (signatureBuilder_ == null) {
          signatureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature, cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Signature.Builder, cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.SignatureOrBuilder>(
                  getSignature(),
                  getParentForChildren(),
                  isClean());
          signature_ = null;
        }
        return signatureBuilder_;
      }

      private long fee_ ;
      /**
       * <code>int64 fee = 4;</code>
       */
      public long getFee() {
        return fee_;
      }
      /**
       * <code>int64 fee = 4;</code>
       */
      public Builder setFee(long value) {
        
        fee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 fee = 4;</code>
       */
      public Builder clearFee() {
        
        fee_ = 0L;
        onChanged();
        return this;
      }

      private long expire_ ;
      /**
       * <code>int64 Expire = 5;</code>
       */
      public long getExpire() {
        return expire_;
      }
      /**
       * <code>int64 Expire = 5;</code>
       */
      public Builder setExpire(long value) {
        
        expire_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 Expire = 5;</code>
       */
      public Builder clearExpire() {
        
        expire_ = 0L;
        onChanged();
        return this;
      }

      private long nonce_ ;
      /**
       * <code>int64 nonce = 6;</code>
       */
      public long getNonce() {
        return nonce_;
      }
      /**
       * <code>int64 nonce = 6;</code>
       */
      public Builder setNonce(long value) {
        
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 nonce = 6;</code>
       */
      public Builder clearNonce() {
        
        nonce_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>string to = 7;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string to = 7;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to = 7;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string to = 7;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>string to = 7;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Transaction)
    }

    // @@protoc_insertion_point(class_scope:Transaction)
    private static final cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction();
    }

    public static cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Transaction>
        PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    public cn.chain33.javasdk.model.protobuf.TransactionProtoBuf.Transaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Signature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Signature_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Transaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Transaction.proto\":\n\tSignature\022\n\n\002ty\030\001" +
      " \001(\005\022\016\n\006pubkey\030\002 \001(\014\022\021\n\tsignature\030\003 \001(\014\"" +
      "\205\001\n\013Transaction\022\016\n\006execer\030\001 \001(\014\022\017\n\007paylo" +
      "ad\030\002 \001(\014\022\035\n\tsignature\030\003 \001(\0132\n.Signature\022" +
      "\013\n\003fee\030\004 \001(\003\022\016\n\006Expire\030\005 \001(\003\022\r\n\005nonce\030\006 " +
      "\001(\003\022\n\n\002to\030\007 \001(\tB\'\n\020com.fuzamei.chain33api.coinB\023Tra" +
      "nsactionProtoBufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Signature_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Signature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Signature_descriptor,
        new java.lang.String[] { "Ty", "Pubkey", "Signature", });
    internal_static_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Transaction_descriptor,
        new java.lang.String[] { "Execer", "Payload", "Signature", "Fee", "Expire", "Nonce", "To", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
